### PR TITLE
[execution] Fix missing SnapshotModuleView method

### LINKED ISSUE #19495: [Bug] Fuzzing build failure due to missing ModuleStorage method in SnapshotModuleView
**Root Cause Analysis**
This issue stems from a mismatch between the ModuleStorage trait definition and its implementation in SnapshotModuleView.
In third_party/move/move-vm/runtime/src/storage/module_storage.rs, the method unmetered_get_module_skip_verification was introduced to the ModuleStorage trait under conditional compilation #[cfg(fuzzing)]. While this method becomes a mandatory part of the trait during fuzzing builds, the implementation for SnapshotModuleView in aptos-move/block-executor/src/captured_reads.rs omitted it.
This omission was introduced in commit faed5637e ("[vm] Fix async code state replay", 2026-01-29), which implemented the trait for the new struct but did not account for fuzzing-specific requirements. Consequently, the compiler reports error[E0046] during fuzzing-enabled builds.

**Error Message**
```
Step #3 - "compile-libfuzzer-address-x86_64": error[E0046]: not all trait items implemented, missing: `unmetered_get_module_skip_verification`
Step #3 - "compile-libfuzzer-address-x86_64":   --> aptos-move/block-executor/src/captured_reads.rs:1359:1
Step #3 - "compile-libfuzzer-address-x86_64":    |
Step #3 - "compile-libfuzzer-address-x86_64": 1359 | impl ModuleStorage for SnapshotModuleView<'_> {
Step #3 - "compile-libfuzzer-address-x86_64":    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `unmetered_get_module_skip_verification` in implementation
```

**Problem Reproduction**
By downloading the aptos-core and oss-fuzz source code repositories from 2026.1.30 to the current time period locally, and executing the following command in oss-fuzz, the problem can be reproduced.
`python infra/helper.py build_fuzzers aptos-core <the local path of aptos-core> --sanitizer address --engine libfuzzer --architecture x86_64`

**Proposed Fix**
Implement unmetered_get_module_skip_verification for SnapshotModuleView by delegating to the existing lazy loading logic, guarded by the #[cfg(fuzzing)] attribute to maintain trait parity across all build profiles.

This fix has already passed ./scripts/rust_lint.sh, as well as local fuzzing build and fuzzing check validation.

Image

**Fuzzing check validation**

Image

## Additional context
Fuzzing build error log: [https://oss-fuzz-build-logs.storage.googleapis.com/log-1e1bfd31-dbd4-4590-bc46-062851abd8e5.txt](url)

### PR DESCRIPTION
**Pull request by xingyaner**
Commit faed5637e ("[vm] Fix async code state replay", 2026-01-29) introduced SnapshotModuleView but omitted the implementation of unmetered_get_module_skip_verification, which is required when the fuzzing feature is enabled.

This leads to E0046 errors in fuzzing pipelines as the method is mandated by the ModuleStorage trait under #[cfg(fuzzing)].

Error Message
```
Step #3 - "compile-libfuzzer-address-x86_64": error[E0046]: not all trait items implemented, missing: `unmetered_get_module_skip_verification`
Step #3 - "compile-libfuzzer-address-x86_64":   --> aptos-move/block-executor/src/captured_reads.rs:1359:1
Step #3 - "compile-libfuzzer-address-x86_64":    |
Step #3 - "compile-libfuzzer-address-x86_64": 1359 | impl ModuleStorage for SnapshotModuleView<'_> {
Step #3 - "compile-libfuzzer-address-x86_64":    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `unmetered_get_module_skip_verification` in implementation
```

This commit resolves the issue by implementing the missing method and guarding it with the appropriate conditional compilation attribute.

Fixes #19495 

---

> [!NOTE]
> **Low Risk**
> A small, `#[cfg(fuzzing)]`-gated stub method to satisfy a trait; it doesn’t affect production code paths.
> 
> **Overview**
> Fixes fuzzing builds by adding the missing `ModuleStorage` trait method `unmetered_get_module_skip_verification` to `SnapshotModuleView` in `captured_reads.rs`, gated behind `#[cfg(fuzzing)]`.
> 
> The new implementation is a stub that returns `Ok(None)`, ensuring the snapshot module resolver compiles when fuzzing is enabled without changing normal (non-fuzzing) execution behavior.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit d31bc9716fd0141d9b1b10518602c55b90383043. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: aptos-move/block-executor/src/captured_reads.rs [hunk 1]
```diff
@@ -1461,6 +1461,14 @@ impl ModuleStorage for SnapshotModuleView<'_> {
             },
         }
     }
+    #[cfg(fuzzing)]
+    fn unmetered_get_module_skip_verification(
+        &self,
+        address: &AccountAddress,
+        module_name: &IdentStr,
+    ) -> VMResult<Option<Arc<Module>>> {
+        self.unmetered_get_lazily_verified_module(&ModuleId::new(*address, module_name.to_owned()))
```
Comment (georgemitenkov) [inline aptos-move/block-executor/src/captured_reads.rs]: This does not seem correct, we are returning here verified module? Let's just return `Ok(None)`?

Comment (xingyaner) [reply aptos-move/block-executor/src/captured_reads.rs]: I understand what you mean. Returning Ok(None) is undoubtedly safer. I have updated the PR, and this version has also passed the /scripts/rust_lint.sh check and the OSS-Fuzz check_build verification.

**Review by georgemitenkov — APPROVED** [review]

File: aptos-move/block-executor/src/captured_reads.rs (hunk 1 above)
Comment (georgemitenkov) [reply aptos-move/block-executor/src/captured_reads.rs]: Thanks!
