### ISSUE TITLE
[Bug] e2e-testsuite build failure due to commit 33a82b2642

### ISSUE THREAD

**Issue by so-schen** [aptos-labs/aptos-core#10093]
# 🐛 Bug

On the main branch, the `language-e2e-testsuite` build failed.
```
error[E0277]: the trait bound `AccountAddress: Arbitrary` is not satisfied
   --> aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs:860:9
    |
860 |         new_voter: AccountAddress,
    |         ^^^^^^^^^ the trait `Arbitrary` is not implemented for `AccountAddress`
    |
```
I run the `git bisect` and locate the faulty commit is 
`* 33a82b2642 (HEAD) [dep] moving testing features out from dependencies`

**Comment by wrwg** [comment]
@gedigi FYI -- I thought we implemented this before, but perhaps not. It should definitely be implemented for fuzzing.

**Comment by gedigi** [comment]
> @gedigi FYI -- I thought we implemented this before, but perhaps not. It should definitely be implemented for fuzzing.

this is indeed implemented, gated with `feature=fuzzing` / `cfg=test` ([code pointer](https://github.com/aptos-labs/aptos-core/blob/main/third_party/move/move-core/types/src/account_address.rs#L13-L14)) and also used in a fuzzer `AccountAddress` ([code pointer](https://github.com/aptos-labs/aptos-core/blob/main/testsuite/fuzzer/fuzz/fuzz_targets/move/execute_entry_function.rs#L24))

was this error produced by `cargo test` ?

**Comment by so-schen** [comment]
> was this error produced by `cargo test` ?

yes, produced by `cargo test`, and if enable "move-core-types/fuzzing", then error down to only one.
But looking at the codes, it seems the cfg `test` flag is not taking effect...

```
error[E0432]: unresolved import `aptos_types::test_helpers`
  --> aptos-move/e2e-testsuite/src/tests/verify_txn.rs:17:5
   |
17 |     test_helpers::transaction_test_helpers,
   |     ^^^^^^^^^^^^ could not find `test_helpers` in `aptos_types`
```

**Comment by so-schen** [comment]
Hi, it takes so long time for aptos team to review the PR that may fix this issue, this might discourage contributor to improve the upstream project

**Comment by so-schen** [comment]
I understand priority for the issue is low, in fact, I was trying to fix a test case and blocked by this issue
see https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/e2e-testsuite/src/tests/execution_strategies.rs
the test cases there are in fact is not checking the verdict, `execute_block` in fact failed due to incorrect sequence number, and the case does not detect that.
maybe it is good that aptos team can clarify that these cases are no longer used.
