### ISSUE TITLE
[Bug] Fuzzing build failure due to missing ModuleStorage method in SnapshotModuleView

### ISSUE THREAD

**Issue by xingyaner** [aptos-labs/aptos-core#19495]
**Root Cause Analysis**
This issue stems from a mismatch between the ModuleStorage trait definition and its implementation in SnapshotModuleView.
In third_party/move/move-vm/runtime/src/storage/module_storage.rs, the method unmetered_get_module_skip_verification was introduced to the ModuleStorage trait under conditional compilation #[cfg(fuzzing)]. While this method becomes a mandatory part of the trait during fuzzing builds, the implementation for SnapshotModuleView in aptos-move/block-executor/src/captured_reads.rs omitted it.
This omission was introduced in commit faed5637e ("[vm] Fix async code state replay", 2026-01-29), which implemented the trait for the new struct but did not account for fuzzing-specific requirements. Consequently, the compiler reports error[E0046] during fuzzing-enabled builds.

**Error Message**
```
Step #3 - "compile-libfuzzer-address-x86_64": error[E0046]: not all trait items implemented, missing: `unmetered_get_module_skip_verification`
Step #3 - "compile-libfuzzer-address-x86_64":   --> aptos-move/block-executor/src/captured_reads.rs:1359:1
Step #3 - "compile-libfuzzer-address-x86_64":    |
Step #3 - "compile-libfuzzer-address-x86_64": 1359 | impl ModuleStorage for SnapshotModuleView<'_> {
Step #3 - "compile-libfuzzer-address-x86_64":    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `unmetered_get_module_skip_verification` in implementation
```

**Problem Reproduction**
By downloading the aptos-core and oss-fuzz source code repositories from 2026.1.30 to the current time period locally, and executing the following command in oss-fuzz, the problem can be reproduced.
`python infra/helper.py build_fuzzers aptos-core <the local path of aptos-core> --sanitizer address --engine libfuzzer --architecture x86_64`

**Proposed Fix**
Implement unmetered_get_module_skip_verification for SnapshotModuleView by delegating to the existing lazy loading logic, guarded by the #[cfg(fuzzing)] attribute to maintain trait parity across all build profiles.

This fix has already passed ./scripts/rust_lint.sh, as well as local fuzzing build and fuzzing check validation.

<img width="1631" height="1144" alt="Image" src="https://github.com/user-attachments/assets/83cbc1e5-2984-4386-b3b3-8c90debc88cc" />

**Fuzzing check validation**

<img width="1763" height="843" alt="Image" src="https://github.com/user-attachments/assets/2e0e824c-7867-42b5-912b-0b50f15c30f0" />

## Additional context
Fuzzing build error log: [https://oss-fuzz-build-logs.storage.googleapis.com/log-1e1bfd31-dbd4-4590-bc46-062851abd8e5.txt](url)

**Comment by georgemitenkov** [comment]
Thanks for reporting and submitting a fix!

**Comment by xingyaner** [comment]
Thank you for the positive feedback! I'm happy to contribute to aptos-core.
