### ISSUE TITLE
[Bug] Compilation failed(Conflicting dependencies found: package 'MoveStdlib' conflicts with 'MoveStdlib') with cli-v2.5.0, but works with cli-v2.4.0

### ISSUE THREAD

**Issue by Alivers** [aptos-labs/aptos-core#12380]
# 🐛 Bug

CLI-v2.5.0:
<img width="1244" alt="image" src="https://github.com/aptos-labs/aptos-core/assets/35741377/610ec614-7fb2-49ca-b2e1-05262055b624">

**Comment by vgao1996** [comment]
Thanks for reporting this issue! 

Can you help us figure out a way to reproduce this locally? That will allow us to better pinpoint the root cause and try out fixes.
